logger:
  level: DEBUG
  fileName: backup.log

server:
  port: 62222
  timeout: 2
mysql:
  -
    addr: jd:3306
    user: root
    password: 123456
    db: wiseidci
    tag: 嘉定园区
  -
    addr: wgq:3308
    user: root
    password: 123456
    db: wiseidci
    tag: 外高桥园区
fetch:
  timeout: 10
  serverPath: /
  storePath: ./myftp
  filters: ".so|CSMain|yklog"
  factor: 2
  interval: 1 #hours
  retain: 5 #保留zip数量

retry:
  retryInterval: 8 #hours
  thresholdFactor: 0.25 #错误递增因子
  maxFailed: 10 #最大尝试次数

email:
    endpoint:
    receivers:
      - 001250120@mails.icbc
accounts:
  - userName: root
    password: root
  - userName: root
    password: Sbbdlyx123

