Logger:
  Level: DEBUG
  FileName:

Server:
  Port: 62222
  Timeout: 2
  List:
    - 192.168.1.3
    - 192.168.1.4
    - 192.168.1.5
Fetch:
  Timeout: 10
  ServerPath: /
  StorePath: /Users/lch/myftp
  Regexp: .*(exe)$


Account:
  UserName: demo
  Password: demo


