Logger:
  Level: DEBUG
  FileName:

Server:
  Port: 62222
  Timeout: 2
  List:
    JD:
      - 192.168.43.150
    WGQ:
      - 192.168.43.2
Fetch:
  Timeout: 10
  ServerPath: /
  StorePath: /Users/lch/myftp
  Filters: ".so|CSMain|yklog"
  Factor: 2

Account:
  UserName: demo
  Password: demo


